// app/layout.js
import "./globals.css";
import Header from "./component/Header";
import Footer from "./component/Footer";
import { Providers } from "./component/Providers";
import { Inter, Roboto_Mono } from "next/font/google";

// Import Google Fonts
const inter = Inter({
  variable: "--font-sans",
  subsets: ["latin"],
});

const robotoMono = Roboto_Mono({
  variable: "--font-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "TechBuildPC",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${inter.variable} ${robotoMono.variable}`}>
      <body className="antialiased">
        <Providers>
          <Header />
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
